### ISSUE TITLE
Invert the progress bar?

### ISSUE THREAD

**Issue by klppl** [michaellee/year-left#1]
It would probably make more sense (to me atleast) if the bar could be inverted. 
Tried to do it by myself, but couldn't do it :)

If I put a integer in timeLeft it works, but when I do the calculaiton it fails...

**Comment by michaellee** [comment]
Hey @dalecarlian are you talking about reversing the progress graphic? Instead of decreasing from right to left, are you saying it should decrease from left to right?

**Comment by klppl** [comment]
@michaellee I meant like the other that this one was inspired from https://twitter.com/year_progress

It makes more sense to me to show progress instead of the bar decreasing :)

**Comment by michaellee** [comment]
Ahhhh I see. Yeah that was intentional in the design for year left. Hence the name. Increasing makes sense for progress since it should show how much the year has progressed. Year left is to create urgency since it shows you, you don't have much of the year left. Hence why I decrease instead of increase. But if you think the inverse makes more sense to you, you're more than welcome to remix the code to make it work the way you think it should work :) Go wild with it!
